package keys

const OS_ENV_OCP_APIM_SUBSCRIPTION_KEY = "OCP_APIM_SUBSCRIPTION_KEY"
const OS_ENV_GEMINI_API_KEY = "GEMINI_API_KEY"
const OS_ENV_USERNAME = "USERNAME"
const OS_ENV_PASSWORD = "PASSWORD"
const OS_ENV_JWT_SECRET = "JWT_SECRET"
